### ISSUE TITLE
v-lazy fires twice

### ISSUE THREAD

**Issue by m-kiss86** [hilongjw/vue-lazyload#389]
I am using the v-lazy on the <img> element.

Lazy load works fine, however, the issue is the request fires twice?

`import VueLazyload from 'vue-lazyload';
Vue.use(VueLazyload, { attempt: 1, preLoad: 1 });

<img v-lazy="'{{asset('/images/svg/personalise.svg')}}'" class="lazy" alt="Personalise Icon">
`

I am using this inside the Blade file in the Laravel project.

<img width="702" alt="Screenshot 2019-08-02 at 13 23 42" src="https://user-images.githubusercontent.com/22741997/62369817-c6321100-b528-11e9-89d3-6a88901a1fdb.png">

**Comment by Brittani** [comment]
i am also has this issue

**Comment by nonlinearcom** [comment]
Same here, did anyone find a solution?

**Comment by blowsie** [comment]
Same issue for me, kind of makes this plugin a bit useless.

**Comment by leovdw** [comment]
Same issue here

**Comment by raisezhang** [comment]
Same issue here

**Comment by cewald** [comment]
Same here

**Comment by raisezhang** [comment]
I found that if the disabled cache was turned on, there would be two requests.
Disabled this option won't have this problem.

Turn on ```Disable cache```：

![image](https://user-images.githubusercontent.com/1481983/66533142-74b78b00-eb44-11e9-8eba-345e9baeb721.png)


Turn off ```Disable cache```：

![image](https://user-images.githubusercontent.com/1481983/66534422-c06c3380-eb48-11e9-9aec-97420470b680.png)

**Comment by Merott** [comment]
While this is unlikely to be a problem in production because of browser's caching behaviour, it still should be fixed.

**Comment by CarlSome** [comment]
> While this is unlikely to be a problem in production because of browser's caching behaviour, it still should be fixed.

Would you please further explain why it's unlikely to be a problem? It seems that the superfluous request does affect the performance of the website.

**Comment by hcmlopes** [comment]
> > While this is unlikely to be a problem in production because of browser's caching behaviour, it still should be fixed.
> 
> Would you please further explain why it's unlikely to be a problem? It seems that the superfluous request does affect the performance of the website, as the Waterfall chart showed in Chrome and my test result.

I believe the reason for the comment "unlikely to be a problem in production" is because a normal user won't be opening their dev tools and browsing with cache disabled, however as mentioned it should still be fixed. I am still experiencing this issue two years later.

**Comment by naimlatifi5** [comment]
Hi, 

I am actually having the same issue even though I turned off "disable cache" still getting two request to same image. Any fix on this ?

**Comment by ITcx1212** [comment]
I'm having the same issue，how to resolve it ?

**Comment by ITcx1212** [comment]
> Hi,
> 
> I am actually having the same issue even though I turned off "disable cache" still getting two request to same image. Any fix on this ?

Have you resolved it?
